

Product.create!([
  {name: "Goggles", price: "12.0", vendor: nil, description: "To help you see under water", image: "test", in_stock: nil},
  {name: "Boots", price: "23.0", vendor: nil, description: "To help you walk up mountains", image: "test", in_stock: nil},
  {name: "Intelligent Bronze Car", price: "3.0", vendor: nil, description: "Computers, Baby & Toys", image: "Iron", in_stock: nil},
  {name: "Fantastic Leather Shirt", price: "74.0", vendor: nil, description: "Baby, Outdoors & Books", image: "Leather", in_stock: nil},
  {name: "Gorgeous Plastic Pants", price: "20.0", vendor: nil, description: "Tools & Automotive", image: "Steel", in_stock: nil},
  {name: "Fantastic Concrete Pants", price: "91.0", vendor: nil, description: "Health & Outdoors", image: "Bronze", in_stock: nil},
  {name: "Rustic Bronze Wallet", price: "9.0", vendor: nil, description: "Toys", image: "Paper", in_stock: nil},
  {name: "Sleek Wool Car", price: "25.0", vendor: nil, description: "Health, Garden & Baby", image: "Wool", in_stock: nil},
  {name: "Lightweight Copper Bag", price: "82.0", vendor: nil, description: "Games", image: "Linen", in_stock: nil},
  {name: "Ergonomic Aluminum Shoes", price: "99.0", vendor: nil, description: "Industrial & Clothing", image: "Concrete", in_stock: nil},
  {name: "Incredible Wool Coat", price: "37.0", vendor: nil, description: "Electronics, Automotive & Outdoors", image: "Granite", in_stock: nil},
  {name: "Enormous Plastic Car", price: "85.0", vendor: nil, description: "Garden", image: "Linen", in_stock: nil},
  {name: "Rustic Plastic Computer", price: "1.0", vendor: nil, description: "Garden", image: "Rubber", in_stock: nil},
  {name: "Practical Steel Table", price: "94.0", vendor: nil, description: "Movies & Books", image: "Bronze", in_stock: nil},
  {name: "Lightweight Granite Computer", price: "39.0", vendor: nil, description: "Home & Grocery", image: "Steel", in_stock: nil},
  {name: "Incredible Concrete Shirt", price: "32.0", vendor: nil, description: "Health, Grocery & Shoes", image: "Rubber", in_stock: nil},
  {name: "Gorgeous Rubber Bag", price: "22.0", vendor: nil, description: "Baby", image: "Paper", in_stock: nil},
  {name: "Mediocre Silk Keyboard", price: "15.0", vendor: nil, description: "Electronics & Outdoors", image: "Concrete", in_stock: nil},
  {name: "Synergistic Bronze Bag", price: "46.0", vendor: nil, description: "Music & Outdoors", image: "Plastic", in_stock: nil},
  {name: "Fantastic Silk Wallet", price: "46.0", vendor: nil, description: "Electronics, Jewelry & Garden", image: "Rubber", in_stock: nil},
  {name: "Enormous Steel Coat", price: "35.0", vendor: nil, description: "Electronics, Jewelry & Kids", image: "Copper", in_stock: nil},
  {name: "Intelligent Bronze Shoes", price: "82.0", vendor: nil, description: "Jewelry & Beauty", image: "Steel", in_stock: nil},
  {name: "Awesome Linen Plate", price: "17.0", vendor: nil, description: "Games", image: "Plastic", in_stock: nil},
  {name: "Practical Concrete Table", price: "2.0", vendor: nil, description: "Home, Sports & Jewelry", image: "Wooden", in_stock: nil},
  {name: "Fantastic Silk Bench", price: "73.0", vendor: nil, description: "Music & Jewelry", image: "Copper", in_stock: nil},
  {name: "Enormous Steel Bottle", price: "69.0", vendor: nil, description: "Toys & Baby", image: "Wooden", in_stock: nil},
  {name: "Mediocre Linen Watch", price: "12.0", vendor: nil, description: "Clothing, Health & Beauty", image: "Leather", in_stock: nil},
  {name: "Incredible Aluminum Table", price: "41.0", vendor: nil, description: "Computers", image: "Paper", in_stock: nil},
  {name: "Fantastic Concrete Chair", price: "28.0", vendor: nil, description: "Clothing & Outdoors", image: "Linen", in_stock: nil},
  {name: "Ergonomic Copper Knife", price: "45.0", vendor: nil, description: "Toys", image: "Wool", in_stock: nil},
  {name: "Durable Cotton Chair", price: "25.0", vendor: nil, description: "Tools, Movies & Health", image: "Granite", in_stock: nil},
  {name: "Fantastic Silk Shirt", price: "41.0", vendor: nil, description: "Sports, Shoes & Automotive", image: "Silk", in_stock: nil},
  {name: "Fantastic Marble Car", price: "19.0", vendor: nil, description: "Health", image: "Wooden", in_stock: nil},
  {name: "Aerodynamic Steel Bag", price: "31.0", vendor: nil, description: "Industrial", image: "Copper", in_stock: nil},
  {name: "Heavy Duty Leather Keyboard", price: "68.0", vendor: nil, description: "Health & Outdoors", image: "Silk", in_stock: nil},
  {name: "Enormous Linen Computer", price: "4.0", vendor: nil, description: "Baby & Industrial", image: "Plastic", in_stock: nil},
  {name: "Awesome Wool Coat", price: "94.0", vendor: nil, description: "Sports & Shoes", image: "Silk", in_stock: nil},
  {name: "Fantastic Copper Plate", price: "79.0", vendor: nil, description: "Garden & Clothing", image: "Steel", in_stock: nil},
  {name: "Enormous Silk Car", price: "26.0", vendor: nil, description: "Automotive & Books", image: "Paper", in_stock: nil},
  {name: "Lightweight Concrete Plate", price: "67.0", vendor: nil, description: "Clothing & Health", image: "Cotton", in_stock: nil},
  {name: "Enormous Leather Lamp", price: "11.0", vendor: nil, description: "Jewelry, Computers & Home", image: "Rubber", in_stock: nil},
  {name: "Awesome Marble Shoes", price: "5.0", vendor: nil, description: "Toys & Tools", image: "Bronze", in_stock: nil},
  {name: "Aerodynamic Linen Bag", price: "68.0", vendor: nil, description: "Games", image: "Plastic", in_stock: nil},
  {name: "Intelligent Cotton Plate", price: "8.0", vendor: nil, description: "Electronics", image: "Cotton", in_stock: nil},
  {name: "Incredible Copper Lamp", price: "97.0", vendor: nil, description: "Health & Music", image: "Linen", in_stock: nil},
  {name: "Mediocre Copper Shoes", price: "80.0", vendor: nil, description: "Games", image: "Steel", in_stock: nil},
  {name: "Fantastic Concrete Computer", price: "25.0", vendor: nil, description: "Movies, Grocery & Industrial", image: "Linen", in_stock: nil},
  {name: "Small Silk Clock", price: "25.0", vendor: nil, description: "Garden & Sports", image: "Granite", in_stock: nil},
  {name: "Intelligent Leather Bag", price: "10.0", vendor: nil, description: "Grocery", image: "Concrete", in_stock: nil},
  {name: "Railsplitter", price: "52.0", vendor: "Garfield", description: "Cuts down trees once per day", image: nil, in_stock: nil},
  {name: "Hookshot", price: "100.0", vendor: "Link", description: "Will get you into trouble with chickens", image: nil, in_stock: nil},
  {name: "Hookshot", price: "43.0", vendor: "Link", description: "asdasdaa", image: "test", in_stock: nil},
  {name: "Tennis Shoes", price: "14.0", vendor: "Adidas", description: "Makes you Run", image: nil, in_stock: 1},
  {name: "Shoes", price: "14.0", vendor: "Adidas", description: "They help you Run", image: nil, in_stock: 1}
])
